"""Create mandates and agents tables

Revision ID: 576c2f2821ce
Revises: 
Create Date: 2025-10-03 02:40:05.336190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '576c2f2821ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_address', sa.String(length=42), nullable=False),
    sa.Column('intent_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandates_nonce'), 'mandates', ['nonce'], unique=False)
    op.create_index(op.f('ix_mandates_user_id'), 'mandates', ['user_id'], unique=False)
    op.create_table('agents',
    sa.Column('mandate_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_mandate_id'), 'agents', ['mandate_id'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_mandate_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_mandates_user_id'), table_name='mandates')
    op.drop_index(op.f('ix_mandates_nonce'), table_name='mandates')
    op.drop_table('mandates')
    # ### end Alembic commands ###
